version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  generate-password:
    secrets:
      - pguser
      - pgpassword
      - pgdatabase
      - encryption-key
    lang: python3-http
    handler: ./generate-password
    image: em1epsi/generate-password:1.4


